In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
x = np.array([[1. , -1. , 2.0] , 
             [2. , 0. , 0.] , 
             [0. , 1. , -1.]])

In [3]:
x_scaled = preprocessing.scale(x)
## it makes mean to be 0 
## and variance to be 1

## whenever we are scaling the feature we have to scale 
## the combine training and testing data otherwise it lead to 
## a hughe error

## but in case , when testing come after completion of the algorithm
## then it would lead to an error , and we need some type of scaling factor
## so that we can swcale our testing data as well in future
x_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [4]:
x_scaled.mean(axis = 0)

array([0., 0., 0.])

In [5]:
x_scaled.std(axis = 0)

array([1., 1., 1.])

In [6]:
scaler = preprocessing.StandardScaler()
scaler.fit(x)

scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
x_test = [[1,1,0]]
scaler.transform(x_test)

array([[ 0.        ,  1.22474487, -0.26726124]])

In [8]:
### example
import numpy as np
# import sklearn.preprocessing import StandardScaler
data = [[0 , 3] , [9 , 4] , [2 , 7] ,[1 , 1]]
# scaler = StandardScaler()
scaler = preprocessing.StandardScaler()
scaler.fit(data)
first = scaler.transform(data)
second = scaler.transform([[2 , 13] , [1 , 4] , [10 , 7] , [1 , 9]])
print(first.sum())
print(second.sum())

0.0
8.879529301279849
