## TensorFlow
TensorFlow is an open-source software library for dataflow programming across a range of tasks. It is a symbolic math library, and is also used for machine learning applications such as neural networks. It is used for both research and production at Google, often replacing its closed-source predecessor, DistBelief.

TensorFlow computations are expressed as stateful dataflow graphs. The name TensorFlow derives from the operations that such neural networks perform on multidimensional data arrays. These arrays are referred to as "tensors". In June 2016, Dean stated that 1,500 repositories on GitHub mentioned TensorFlow, of which only 5 were from Google.

TensorFlow is cross-platform. It runs on nearly everything: GPUs and CPUs—including mobile and embedded platforms—and even tensor processing units (TPUs), which are specialized hardware to do tensor math on.

![title](1tensorflow.png)


The TensorFlow distributed execution engine abstracts away the many supported devices and provides a high performance-core implemented in C++ for the TensorFlow platform.
On top of that sit the Python and C++ frontends (with more to come). The Layers API provides a simpler interface for commonly used layers in deep learning models. On top of that sit higher-level APIs, including Keras (more on the Keras.io site) and the Estimator API, which makes training and evaluating distributed models easier.

# 1) How to install and Import Tensorflow ??

In [1]:
## Commands to install tensorflow
# 1. conda install tensorflow
# 2. conda install tensorflow-gpu
# 3. pip install tensorflow ( run anaconda prompt as administration)

## tensorflow has basically 2 version v1 , v2

## version 1
import tensorflow as tf
## to install version go to anaconda navigator after completing the above steps 
## and change tenserflow version to 1.5.0
## keras version to 2.3.1

## version v2
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()

# ## to remove the message warning from version 2
# import tensorflow.python.util.deprecation as deprecation
# deprecation._PRINT_DEPRECATION_WARNINGS = False




######################
print(tf.__version__)

1.15.0


# 2) Constant

In [2]:
a = tf.constant(2) ## it is Tensor type of an object
b = tf.constant(3)
c = a + b
a , b , c

(<tf.Tensor 'Const:0' shape=() dtype=int32>,
 <tf.Tensor 'Const_1:0' shape=() dtype=int32>,
 <tf.Tensor 'add:0' shape=() dtype=int32>)

In [3]:
sess = tf.Session()
c_val , a_val = sess.run(c) , sess.run(a)
a_val , c_val , type(a_val)

(2, 5, numpy.int32)

In [4]:
a1 = tf.constant([[3 , 3]])
a2 = tf.constant([[3] , [3]])
a3 = tf.matmul(a1 , a2)
## we can't change the value of constant once it assign
sess.run(a3)

array([[18]])

In [5]:
a = tf.constant(1)
a = tf.constant(2)
## Here we aren’t changing the constant, we have created another constant with different value. 
## Python variable a is not a constant.
a

<tf.Tensor 'Const_5:0' shape=() dtype=int32>

# 3) Session

In [6]:
a = tf.constant(2)
b = tf.constant(3)
c = a + b
c = tf.add(a , c)
# print(c.eval()) ## there is no default session
with tf.Session() as sess:
    ## this sess object will work within this block
    print(c.eval())

7


# 4) Variables

In [7]:
var1 = tf.Variable(100) ## right now it is an un - initialize variable
var2 = tf.Variable(3)
sum = tf.add(var1 , var2)
sess = tf.Session()
sess.run(tf.global_variables_initializer()) ## it is use to make all variable global and to initialize them 
sess.run(sum)

103

In [8]:
assign = var1.assign(1232)
print(sess.run(var1))
print(sess.run(sum))
sess.run(assign)
print(sess.run(var1))
print(sess.run(sum))


100
103
1232
1235


# 5) Placeholder

In [9]:
x = tf.placeholder(tf.int32 , shape = (2 , 3)) ## by default it is shape = ()
y = x * tf.constant(12)
# sess.run(y) ## give error!!!!!
sess.run(y , feed_dict = {x : [[1 , 2 , 3] , [4 , 5 , 6]]})

array([[12, 24, 36],
       [48, 60, 72]])

# 6) MNIST 

### a) Load the data..........

In [35]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/" , one_hot = True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [11]:
mnist

Datasets(train=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x00000256D2735D08>, validation=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x00000256D035A908>, test=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x00000256D001AE08>)

In [12]:
mnist.train.images.shape , mnist.train.labels.shape
## there are total 55000 flaten images and each images os of dimesion 28 x 28

((55000, 784), (55000, 10))

In [13]:
mnist.train.labels[0] ## labels are hot encoded

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [14]:
mnist.test.images.shape , mnist.test.labels.shape

((10000, 784), (10000, 10))

In [15]:
mnist.validation.images.shape

(5000, 784)

In [16]:
import numpy as np
from matplotlib import pyplot as plt
first_image = mnist.train.images[412]
first_image = np.array(first_image , dtype = 'float')
first_image = first_image.reshape((28 , 28))
plt.imshow(first_image)
plt.show()

<Figure size 640x480 with 1 Axes>

In [17]:
## random_normal
with tf.Session() as sess:
    print(tf.random_normal([784 , 256]).eval())


[[ 1.6934016e+00 -9.0782458e-01 -4.8745263e-02 ...  2.3526177e-01
  -6.7758274e-01  1.1348503e+00]
 [-1.8062690e-02 -9.1168389e-02  5.8441508e-01 ... -3.0736681e-02
   2.7564251e+00  1.7175034e+00]
 [-7.8653109e-01  7.3506099e-01  3.0115053e-01 ... -3.9780074e-01
   6.7218584e-01 -9.0632629e-01]
 ...
 [-9.4026989e-01 -1.0638218e+00  3.7405476e-01 ... -6.7937925e-02
   1.9021906e-01 -1.5895494e+00]
 [-3.5777003e-01  7.1384907e-01  5.6214648e-01 ... -3.6530498e-01
  -7.4618231e-03  7.4879575e-01]
 [ 8.6005408e-01 -2.5310557e-02 -8.8476193e-01 ...  1.4269655e-03
  -6.2718534e-01  2.5962923e-02]]


### b) Intialising weights and biases

In [18]:
n_input = 784
n_hidden_1 = 256
n_hidden_2 = 256
n_classes = 10

weights = {
    "h1" : tf.Variable(tf.random_normal([n_input , n_hidden_1]) ) ,
#     "h1" : tf.Variable(tf.random_normal([n_input , n_hidden_1]) , trainable = False) ,
    "h2" : tf.Variable(tf.random_normal([n_hidden_1 , n_hidden_2])) ,
    "out" : tf.Variable(tf.random_normal([n_hidden_2 , n_classes]))
}

biases = {
    "h1" : tf.Variable(tf.random_normal([n_hidden_1])) , 
    "h2" : tf.Variable(tf.random_normal([n_hidden_2])) , 
    "out" : tf.Variable(tf.random_normal([n_classes]))
}

In [19]:
tf.trainable_variables()

[<tf.Variable 'Variable:0' shape=() dtype=int32_ref>,
 <tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>,
 <tf.Variable 'Variable_2:0' shape=(784, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_3:0' shape=(256, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_4:0' shape=(256, 10) dtype=float32_ref>,
 <tf.Variable 'Variable_5:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_6:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_7:0' shape=(10,) dtype=float32_ref>]

### c) Forward Propagation

In [20]:
def forward_propagation(x , weights , biases):
    in_layer1 = tf.add(tf.matmul(x , weights["h1"]) , biases["h1"])
    out_layer1 = tf.nn.relu(in_layer1)
    
    in_layer2 = tf.add(tf.matmul(out_layer1 , weights["h2"]) , biases["h2"])
    out_layer2 = tf.nn.relu(in_layer2)
    
    output = tf.add(tf.matmul(out_layer2 , weights["out"]) , biases["out"])
    return output

### d) finding the prediction and accuracy

In [21]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
x = tf.placeholder("float" , [None , n_input])
y = tf.placeholder(tf.int32 , [None , n_classes])

In [22]:
## predicted output
pred = forward_propagation(x , weights , biases)
predictions = tf.argmax(pred , 1)
predictions_eval = sess.run(predictions , feed_dict = {x : mnist.test.images})
predictions_eval

array([4, 5, 5, ..., 5, 5, 5], dtype=int64)

In [23]:
## actual labels
true_labels = tf.argmax(y , 1)
labels = sess.run(true_labels , feed_dict = {y : mnist.test.labels})
labels

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [24]:
## correct prediction
correct_predictions = tf.equal(predictions , true_labels)

In [25]:
## other way to run simultanously
predictions_eval , labels , correct_pred = sess.run([predictions , true_labels , correct_predictions] , feed_dict = {x : mnist.test.images , y : mnist.test.labels})
predictions_eval , labels , correct_pred

(array([4, 5, 5, ..., 5, 5, 5], dtype=int64),
 array([7, 2, 1, ..., 4, 5, 6], dtype=int64),
 array([False, False, False, ..., False,  True, False]))

In [26]:
## how many we are getting correct
correct_pred.sum()

1005

### e) cost function

In [27]:
## cross entropy function
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = pred , labels = y))

sess = tf.Session()
sess.run(tf.global_variables_initializer())

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [28]:
sess.run(cost , feed_dict = {x : mnist.train.images , y : mnist.train.labels})

2075.6528

### f) Running the optimizer

In [29]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/" , one_hot = True)

n_input = 784
n_hidden_1 = 256
n_hidden_2 = 256
n_classes = 10

weights = {
    "h1" : tf.Variable(tf.random_normal([n_input , n_hidden_1]) ) ,
    "h2" : tf.Variable(tf.random_normal([n_hidden_1 , n_hidden_2])) ,
    "out" : tf.Variable(tf.random_normal([n_hidden_2 , n_classes]))
}

biases = {
    "h1" : tf.Variable(tf.random_normal([n_hidden_1])) , 
    "h2" : tf.Variable(tf.random_normal([n_hidden_2])) , 
    "out" : tf.Variable(tf.random_normal([n_classes]))
}

print(tf.trainable_variables())

def forward_propagation(x , weights , biases):
    in_layer1 = tf.add(tf.matmul(x , weights["h1"]) , biases["h1"])
    out_layer1 = tf.nn.relu(in_layer1)
    
    in_layer2 = tf.add(tf.matmul(out_layer1 , weights["h2"]) , biases["h2"])
    out_layer2 = tf.nn.relu(in_layer2)
    
    output = tf.add(tf.matmul(out_layer2 , weights["out"]) , biases["out"])
    return output

x = tf.placeholder("float" , [None , n_input])
y = tf.placeholder(tf.int32 , [None , n_classes])
pred = forward_propagation(x , weights , biases)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = pred , labels = y))

optimizer = tf.train.AdamOptimizer(learning_rate =  0.01)
optimize = optimizer.minimize(cost)

# minimize function ===>> finds the derivative(slope) values & chnage the values as per the learning rate
# and the slopes once
## if there is no variable which are trainable then this will give error 
sess = tf.Session()
sess.run(tf.global_variables_initializer())

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[<tf.Variable 'Variable:0' shape=() dtype=int32_ref>, <tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>, <tf.Variable 'Variable_2:0' shape=(784, 256) dtype=float32_ref>, <tf.Variable 'Variable_3:0' shape=(256, 256) dtype=float32_ref>, <tf.Variable 'Variable_4:0' shape=(256, 10) dtype=float32_ref>, <tf.Variable 'Variable_5:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'Variable_6:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'Variable_7:0' shape=(10,) dtype=float32_ref>, <tf.Variable 'Variable_8:0' shape=(784, 256) dtype=float32_ref>, <tf.Variable 'Variable_9:0' shape=(256, 256) dtype=float32_ref>, <tf.Variable 'Variable_10:0' shape=(256, 10) dtype=float32_ref>, <tf.Variable 'Variable_11:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'Variable_12:0' shape=(256,) dtype=float32_ref>, <t

In [30]:
c, _ = sess.run([cost,optimize], feed_dict = {x:mnist.train.images , y:mnist.train.labels})
print(c)
## every time we run it it will reduce the cost

3064.2747


### g) How does the optimizer work ???

In [31]:
## first it will find which variables depends upon cost function and trainable = True
tf.trainable_variables()

[<tf.Variable 'Variable:0' shape=() dtype=int32_ref>,
 <tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>,
 <tf.Variable 'Variable_2:0' shape=(784, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_3:0' shape=(256, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_4:0' shape=(256, 10) dtype=float32_ref>,
 <tf.Variable 'Variable_5:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_6:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_7:0' shape=(10,) dtype=float32_ref>,
 <tf.Variable 'Variable_8:0' shape=(784, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_9:0' shape=(256, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_10:0' shape=(256, 10) dtype=float32_ref>,
 <tf.Variable 'Variable_11:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_12:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_13:0' shape=(10,) dtype=float32_ref>]

### h) running multiple iteration

In [32]:
for i in range(25):
    c , _ = sess.run([cost , optimize] , feed_dict = {x : mnist.train.images , y : mnist.train.labels})
    print(c)

1591.4557
1227.6194
956.62146
790.42633
700.2512
636.4966
568.115
475.92465
378.05542
296.64307
240.86438
206.59113
182.51486
160.35391
140.54857
127.025154
121.070435
120.36418
121.24138
120.207275
115.38292
106.99047
96.912346
87.21384
79.208916


In [33]:
predictions = tf.argmax(pred , 1)
correct_labels = tf.argmax(y , 1)
correct_predictions = tf.equal(predictions , correct_labels)
predictions , correct_predictions = sess.run([predictions , correct_predictions] , feed_dict = {x : mnist.test.images , y : mnist.test.labels})

correct_predictions.sum()

8373

### i) Batch gradient descent

In [34]:
batch_size = 100
for i in range(25):
    num_batches = int(mnist.train.num_examples / batch_size)
    total_cost = 0
    for j in range(num_batches):
        batch_x , batch_y = mnist.train.next_batch(batch_size)
        c , _ = sess.run([cost ,optimize] , feed_dict = {x : batch_x , y : batch_y})
        total_cost += c
    print(total_cost)
    
predictions = tf.argmax(pred , 1)
correct_labels = tf.argmax(y , 1)
correct_predictions = tf.equal(predictions , correct_labels)
predictions , correct_predictions = sess.run([predictions , correct_predictions] , feed_dict = {x : mnist.test.images , y : mnist.test.labels})

correct_predictions.sum()

13997.194191714632
4180.954490777254
2471.177090359046
1591.5871947667051
1420.5042736675387
1265.8064440161677
1001.3624152433226
892.8727606200329
868.5923013933949
805.130439615462
701.7107965899795
585.714692180202
543.4623756766878
466.0597000812766
447.07890364921445
382.8270943195958
397.6262068239175
344.5137250860313
324.015757872116
287.97091303172056
273.14831460513926
233.50156650033304
184.49188855835666
189.29186070472545
183.6027430960331


9621